[global]
debug=off

[transport-udp]
type=transport
protocol=udp
bind=0.0.0.0:5060

[yealink]
type=endpoint
context=from_yealink
disallow=all
allow=opus,ulaw,alaw,gsm
direct_media=no
rtp_symmetric=yes
rewrite_contact=yes
force_rport=yes
auth=yealink_auth
aors=yealink

[yealink_auth]
type=auth
auth_type=userpass
username=yealink
password=password123

[yealink]
type=aor
max_contacts=1

[homeassistant]
type=endpoint
context=to_homeassistant
disallow=all
allow=opus,ulaw,alaw,gsm
direct_media=no
rtp_symmetric=yes
rewrite_contact=yes
from_user=asterisk
from_domain=asterisk.local
outbound_auth=homeassistant_auth
aors=homeassistant

[homeassistant_auth]
type=auth
auth_type=userpass
username=asterisk
password=asterisk

[homeassistant]
type=aor
contact=sip:<homeassistantip>:5060

[homeassistant_identify]
type=identify
endpoint=homeassistant
match=<homeassistantip>
